// GENERATED by tools/launcher.ts scan — do not edit by hand; COMMIT
// the regenerated file (tests/launcher-sim.test.ts asserts freshness).
// The display-side PSP/Vita/Symbian union: the launcher imports it for
// titles + cover asset keys; each host's target-specific appTable
// (spec op 39) stays the runtime truth for what is embedded.

export interface RegistryApp {
  output: string;
  id: string;
  title: string;
  /** Pak image asset of the 256×128 cover. The literal paths below are
   *  what the build's asset collector picks up and bakes. */
  cover: string;
  /** The cover's baked reflection (mirrored + alpha falloff), drawn as
   *  its own quad so the seam stays a geometric straight edge. */
  refl: string;
}

export const REGISTRY: readonly RegistryApp[] = [
  { output: "note-main", id: "dev.pocket-stack.note", title: "Pocket Note", cover: "covers/cover-note-main.png", refl: "covers/refl-note-main.png" },
  { output: "nsengine-main", id: "dev.pocket-stack.nsengine", title: "PocketJS NS Engine", cover: "covers/cover-nsengine-main.png", refl: "covers/refl-nsengine-main.png" },
  { output: "cafe-main", id: "dev.pocket-stack.cafe", title: "PocketJS: Café", cover: "covers/cover-cafe-main.png", refl: "covers/refl-cafe-main.png" },
  { output: "chrome-main", id: "dev.pocket-stack.chrome", title: "PocketJS: Chrome", cover: "covers/cover-chrome-main.png", refl: "covers/refl-chrome-main.png" },
  { output: "cursor-main", id: "dev.pocket-stack.cursor", title: "PocketJS: Cursor", cover: "covers/cover-cursor-main.png", refl: "covers/refl-cursor-main.png" },
  { output: "cards-main", id: "dev.pocket-stack.cards", title: "PocketJS: Feature Cards", cover: "covers/cover-cards-main.png", refl: "covers/refl-cards-main.png" },
  { output: "gallery-main", id: "dev.pocket-stack.gallery", title: "PocketJS: Gallery (L / R paging)", cover: "covers/cover-gallery-main.png", refl: "covers/refl-gallery-main.png" },
  { output: "library-main", id: "dev.pocket-stack.library", title: "PocketJS: Game Library", cover: "covers/cover-library-main.png", refl: "covers/refl-library-main.png" },
  { output: "hero-main", id: "dev.pocket-stack.hero", title: "PocketJS: Hero", cover: "covers/cover-hero-main.png", refl: "covers/refl-hero-main.png" },
  { output: "hero-vue-sfc-main", id: "dev.pocket-stack.hero.vue.sfc", title: "PocketJS: Hero Vue SFC", cover: "covers/cover-hero-vue-sfc-main.png", refl: "covers/refl-hero-vue-sfc-main.png" },
  { output: "hero-vue-vapor-main", id: "dev.pocket-stack.hero.vue.vapor", title: "PocketJS: Hero Vue Vapor", cover: "covers/cover-hero-vue-vapor-main.png", refl: "covers/refl-hero-vue-vapor-main.png" },
  { output: "bench-workloads-main", id: "dev.pocket-stack.bench-workloads", title: "PocketJS: Memory Workloads", cover: "covers/cover-bench-workloads-main.png", refl: "covers/refl-bench-workloads-main.png" },
  { output: "stats-main", id: "dev.pocket-stack.stats", title: "PocketJS: Mission Control", cover: "covers/cover-stats-main.png", refl: "covers/refl-stats-main.png" },
  { output: "motions-main", id: "dev.pocket-stack.motions", title: "PocketJS: Motion Lab (yui540 studies on baked keyframe timelines)", cover: "covers/cover-motions-main.png", refl: "covers/refl-motions-main.png" },
  { output: "notifications-main", id: "dev.pocket-stack.notifications", title: "PocketJS: Notifications", cover: "covers/cover-notifications-main.png", refl: "covers/refl-notifications-main.png" },
  { output: "music-main", id: "dev.pocket-stack.music", title: "PocketJS: Now Playing", cover: "covers/cover-music-main.png", refl: "covers/refl-music-main.png" },
  { output: "settings-main", id: "dev.pocket-stack.settings", title: "PocketJS: Settings", cover: "covers/cover-settings-main.png", refl: "covers/refl-settings-main.png" },
  { output: "im-main", id: "dev.pocket-stack.im", title: "PocketJS: Talk", cover: "covers/cover-im-main.png", refl: "covers/refl-im-main.png" },
  { output: "vue-sfc-lab-main", id: "dev.pocket-stack.vue.sfc.lab", title: "PocketJS: Vue SFC Feature Lab", cover: "covers/cover-vue-sfc-lab-main.png", refl: "covers/refl-vue-sfc-lab-main.png" },
  { output: "iphone16-demo-main", id: "dev.pocket-stack.iphone16-demo", title: "PocketJS: iPhone 16 Hero", cover: "covers/cover-iphone16-demo-main.png", refl: "covers/refl-iphone16-demo-main.png" },
  { output: "zoomlab-main", id: "dev.pocket-stack.zoomlab", title: "Zoom Lab", cover: "covers/cover-zoomlab-main.png", refl: "covers/refl-zoomlab-main.png" },
] as const;
